---

- name: Building SOPe SRPMs
  command: rpmbuild -bb SPECS/sope.spec
  args:
    chdir: "{{ rpmbuild_build_dir }}"
  register: output

- find: 
    paths: "{{ rpmbuild_build_dir }}/RPMS/{{ ansible_userspace_architecture }}"
    pattern: "*debug*"
  register: find_results

- name: Removing SOPe debug sumbols
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ find_results.files }}"

- find:
    path: "{{ rpmbuild_build_dir }}/RPMS/{{ ansible_userspace_architecture }}"
    pattern: "sope49-*.rpm"
  register: sope_results

- set_fact:
    sope_list: "{{ sope_results.files | map(attribute='path') | list | join(' ') }}"

- name: Installing SOPe libraries
  command: yum install -y {{ item.path }}
  with_items:
    - "{{ sope_results.files }}"
  ignore_errors: false
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'

- name: Installing SOPe libraries
  command: rpm -ivh --nodeps {{ sope_list }}
  ignore_errors: false
  when: ansible_facts['distribution'] == 'OracleLinux' and ansible_facts['distribution_major_version'] == '8'

- name: Building SOGo SRPMs
  command: rpmbuild -bb SPECS/sogo.spec
  args:
    chdir: "{{ rpmbuild_build_dir }}"
  register: output

- find:
    paths: "{{ rpmbuild_build_dir }}/RPMS/{{ ansible_userspace_architecture }}"
    pattern: "*debug*"
  register: find_results

- name: Removing SOGo debug sumbols
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ find_results.files }}"

- find:
    path: "{{ rpmbuild_build_dir }}/RPMS/{{ ansible_userspace_architecture }}"
    pattern: "sope49-cards*.rpm"
  register: sogo_results

- name: Installing SOGo Deps libraries
  command: rpm -ivh --nodeps {{ item.path }}
  with_items:
    - "{{ sogo_results.files }}"
  ignore_errors: false

- find:
    path: "{{ rpmbuild_build_dir }}/RPMS/{{ ansible_userspace_architecture }}"
    pattern: "sope49-gdl1-contentstore*.rpm"
  register: sogo_results

- name: Installing SOGo Deps libraries
  command: yum install -y {{ item.path }}
  with_items:
    - "{{ sogo_results.files }}"
  ignore_errors: false

- find:
    path: "{{ rpmbuild_build_dir }}/RPMS/{{ ansible_userspace_architecture }}"
    pattern: "sogo-*.rpm"
  register: sogo_results

- set_fact:
    sogo_list: "{{ sogo_results.files | map(attribute='path') | list | join(' ') }}"

- name: Installing SOGo libraries
  command: yum install -y {{ item.path }}
  with_items:
    - "{{ sogo_results.files }}"
  ignore_errors: true
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'
  
- name: Installing SOGo libraries
  command: rpm -ivh --nodeps {{ sogo_list }}
  ignore_errors: false
  when: ansible_facts['distribution'] == 'OracleLinux' and ansible_facts['distribution_major_version'] == '8'

- name: Creating SOGo symlink
  file:
    src: /usr/lib/GNUstep
    dest: /usr/lib64/GNUstep
    state: link
  when: ansible_facts['distribution'] == 'OracleLinux' and ansible_facts['distribution_major_version'] == '8'

