---

- name: Coping SOGo configuration files
  template: src={{ item }} dest=/etc/sogo/{{ item | basename | regex_replace('\.j2','') }} force=yes
  with_items:
   - sogo/sieve.creds.j2
   - sogo/sogo.conf.j2

- name: Fixing SOGo permissions
  file:
   path: /etc/sogo/{{ item }}
   group: sogo
   mode: "u=rw,g=r,o="
  with_items:
   - sieve.creds
   - sogo.conf

- name: Copying SOGo image files
  copy: src={{ item }} dest=/usr/lib64/GNUstep/SOGo/WebServerResources/img/{{ item }} force=yes
  with_items:
   - sogo-full.svg
   - sogo.ico
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'

- name: Copying SOGo image files
  copy: src={{ item }} dest=/usr/lib/GNUstep/SOGo/WebServerResources/img/{{ item }} force=yes
  with_items:
   - sogo-full.svg
   - sogo.ico
  when: ansible_facts['distribution'] == 'OracleLinux' and ansible_facts['distribution_major_version'] == '8'

